spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mississippi
    username: sa
    password:

  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  # 서버에 사진이 저장됨, 경로
  file:
    path: D:\mssp

logging:
  level:
    org.hibernate.SQL: debug

kakao:
  request:
    url:
      token: https://kauth.kakao.com/oauth/token
      userInfo: https://kapi.kakao.com/v2/user/me
  clientId : 39b1629ce319fa9f89c3b9f947d92255
  redirectUri : http://localhost:8080/oauth
